version: '3.8'

services:
  db:
    image: postgres:15
    container_name: duobrain-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: duobrain
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: duobrain-app
    ports:
      - '3000:3000'
    environment:
      # Make sure this matches your schema.prisma connection
      DATABASE_URL: postgres://postgres:postgres@db:5432/duobrain
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    # Optional: if you want to automatically run migrations on startup
    command: sh -c "npx prisma migrate deploy --schema=./prisma/schema.prisma && npm run dev"

volumes:
  db-data:
